version: '3.8'

services:
  m172dmr:
    image: mfiscus/m172dmr:latest
    platform: linux/arm/v7
    networks:
      - proxy
    volumes:
      - /opt/m172dmr:/config
    environment:
      TZ: 'UTC'
      LOCATION: 'Nowhere'
      DESCRIPTION: 'Multi-Mode Repeater'
      URL: 'www.google.co.uk'
      CALLSIGN: 'AD8DP D'
      LOCALPORT: '32010'
      DSTNAME: 'M17-USA Z'
      DSTADDRESS: '3.138.122.152'
      DSTPORT: '17000'
      GAINADJUSTDB: '-3'
      DAEMON: '0'
      ID: '1234567'
      XLXFILE: '/config/XLXHosts.txt'
      XLXREFLECTOR: '950'
      XLXMODULE: 'D'
      STARTUPDSTID: '4001'
      STARTUPPC: '1'
      ADDRESS: '127.0.0.1'
      PORT: '62030'
      JITTER: '500'
      PASSWORD: 'passw0rd'
      FILE: '/config/DMRIDs.dat'